# Generated by Django 4.0.7 on 2024-01-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='descrpition',
            new_name='description',
        ),
    ]
