# Generated by Django 4.0.7 on 2024-01-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=23.6, max_digits=10),
            preserve_default=False,
        ),
    ]
