# Generated by Django 3.2.9 on 2023-07-10 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_rename_name_cats_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cats',
            old_name='food',
            new_name='foods',
        ),
    ]
