# Generated by Django 3.2.9 on 2023-07-10 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_rename_food_cats_foods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats',
            name='nickname',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Name must be >= 2 characters')], verbose_name='name'),
        ),
    ]
